markdown: kramdown

encoding: "utf-8"

sass:
  sass_dir: css
  style: compressed

widgets:
 -
    name: ggforce
    thumbnail: images/ggforce.png
    url: https://github.com/thomasp85/ggforce
    jslibs: >
    ghuser: thomasp85
    ghrepo: ggforce
    tags: visualization,general
    cran: true
    release:
    examples:
    ghauthor: thomasp85
    short: >
      ggforce is aimed at providing missing functionality to ggplot2 through the extension system introduced with ggplot2 v2.0.0.
    description: >    
    
 -
    name: ggalt
    thumbnail: images/ggalt.png
    url: https://github.com/hrbrmstr/ggalt
    jslibs: >
    ghuser: hrbrmstr
    ghrepo: ggalt
    tags: visualization,general
    cran: true
    release:
    examples:
    ghauthor: hrbrmstr
    short: >
      A compendium of ‘geoms’, ‘coords’ and ‘stats’ for ‘ggplot2’.
    description: > 
      A compendium of ‘geoms’, ‘coords’ and ‘stats’ for ‘ggplot2’, including splines, 1d and 2d densities, univariate average shifted histograms and a new map coordinate system based on the ‘PROJ.4’-library.
 
 -
    name: ggiraph
    thumbnail: images/ggiraph.png
    url: https://github.com/davidgohel/ggiraph
    jslibs: >
    ghuser: davidgohel
    ghrepo: ggiraph
    tags: visualization,general
    cran: true
    release:
    examples:
    ghauthor: davidgohel
    short: >
      htmlwidget to make 'ggplot' graphics interactive.
    description: > 
    
 -
    name: ggstance
    thumbnail: images/ggstance.png
    url: https://github.com/lionel-/ggstance
    jslibs: >
    ghuser: lionel-
    ghrepo: ggstance
    tags: visualization,general
    cran: true
    release:
    examples:
    ghauthor: lionel-
    short: >
      ggstance implements horizontal versions of common ggplot2 geoms.
    description: > 
    
 -
    name: ggrepel
    thumbnail: images/ggrepel.png
    url: https://github.com/slowkow/ggrepel
    jslibs: >
    ghuser: slowkow
    ghrepo: ggrepel
    tags: visualization,general
    cran: true
    release:
    examples:
    ghauthor: slowkow
    short: >
      Repel overlapping text labels away from each other.
    description: > 
    
 -
    name: ggraph
    thumbnail: images/ggraph.png
    url: https://github.com/thomasp85/ggraph
    jslibs: >
    ghuser: thomasp85
    ghrepo: ggraph
    tags: visualization,general
    cran: true
    release:
    examples:
    ghauthor: thomasp85
    short: >
      ggraph is tailored at plotting graph-like data structures (graphs, networks, trees, hierarchies...).
    description: > 
    
 -
    name: ggpmisc
    thumbnail: images/ggpmisc.png
    url: https://bitbucket.org/aphalo/ggpmisc
    jslibs: >
    ghuser: 
    ghrepo: 
    tags: visualization,general
    cran: true
    release:
    examples:
    ghauthor: 
    short: >
      Miscellaneous Extensions to ‘ggplot2’.
    description: >     
    
 -
    name: geomnet
    thumbnail: images/geomnet.png
    url: https://github.com/sctyner/geomnet
    jslibs: >
    ghuser: sctyner
    ghrepo: geomnet
    tags: visualization,general
    cran: true
    release:
    examples:
    ghauthor: sctyner
    short: >
      geomnet implements network visualizations in ggplot2 via geom_net.
    description: >  
    
 -
    name: ggExtra
    thumbnail: images/ggExtra.png
    url: https://github.com/daattali/ggExtra
    jslibs: >
    ghuser: daattali
    ghrepo: ggExtra
    tags: visualization,general
    cran: true
    release:
    examples:
    ghauthor: daattali
    short: >
      ggExtra lets you add marginal density plots or histograms to ggplot2 scatterplots.
    description: > 
    
 -
    name: gganimate
    thumbnail: images/gganimate.gif
    url: https://github.com/dgrtwo/gganimate
    jslibs: >
    ghuser: dgrtwo
    ghrepo: gganimate
    tags: visualization,general
    cran: true
    release:
    examples:
    ghauthor: dgrtwo
    short: >
      gganimate wraps the animation package to create animated ggplot2 plots.
    description: > 
    
 -
    name: plotROC
    thumbnail: images/plotROC.png
    url: https://github.com/sachsmc/plotROC
    jslibs: >
    ghuser: sachsmc
    ghrepo: plotROC
    tags: visualization,general
    cran: true
    release:
    examples:
    ghauthor: sachsmc
    short: >
      plotROC provides functions to generate an interactive ROC curve plot for web use, and print versions.
    description: > 
      
 -
    name: ggthemes
    thumbnail: images/ggthemes.png
    url: https://github.com/jrnold/ggthemes
    jslibs: >
    ghuser: jrnold
    ghrepo: ggthemes
    tags: visualization,general
    cran: true
    release:
    examples:
    ghauthor: jrnold
    short: >
      Some extra geoms, scales, and themes for ggplot.
    description: > 
    
 -
    name: ggspectra
    thumbnail: images/ggspectra.png
    url: https://bitbucket.org/aphalo/ggspectra
    jslibs: >
    ghuser: 
    ghrepo: 
    tags: visualization,general
    cran: true
    release:
    examples:
    ghauthor: 
    short: >
      ggspectra extends ggplot2 with stats, geoms and annotations suitable for light spectra.
    description: > 
    
 -
    name: ggnetwork
    thumbnail: images/ggnetwork.png
    url: https://github.com/briatte/ggnetwork
    jslibs: >
    ghuser: briatte
    ghrepo: ggnetwork
    tags: visualization,general
    cran: true
    release:
    examples:
    ghauthor: briatte
    short: >
      The ggnetwork package provides a way to build network plots with ggplot2.
    description: >    
    
 -
    name: ggtech
    thumbnail: images/ggtech.png
    url: https://github.com/ricardo-bion/ggtech
    jslibs: >
    ghuser: ricardo-bion
    ghrepo: ggtech
    tags: visualization,general
    cran: true
    release:
    examples:
    ghauthor: ricardo-bion
    short: >
      ggplot2 tech themes, scales, and geoms.
    description: >   
    
 -
    name: ggradar
    thumbnail: images/ggradar.png
    url: https://github.com/ricardo-bion/ggradar
    jslibs: >
    ghuser: ricardo-bion
    ghrepo: ggradar
    tags: visualization,general
    cran: true
    release:
    examples:
    ghauthor: ricardo-bion
    short: >
      ggradar allows you to build radar charts with ggplot2.
    description: >     
    
 -
    name: ggTimeSeries
    thumbnail: images/ggTimeSeries.png
    url: https://github.com/Ather-Energy/ggTimeSeries
    jslibs: >
    ghuser: Ather-Energy
    ghrepo: ggTimeSeries
    tags: visualization,general
    cran: true
    release:
    examples:
    ghauthor: Ather-Energy
    short: >
      This R package offers novel time series visualisations.
    description: >         
    
 -
    name: ggtree
    thumbnail: images/ggtree.png
    url: https://bioconductor.org/packages/release/bioc/html/ggtree.html
    jslibs: >
    ghuser: 
    ghrepo: 
    tags: visualization,general
    cran: true
    release:
    examples:
    ghauthor: 
    short: >
      gtree is designed for visualizing phylogenetic tree and different types of associated annotation data.
    description: >   
    
 -
    name: ggseas
    thumbnail: images/ggseas.png
    url: https://github.com/ellisp/ggseas
    jslibs: >
    ghuser: ellisp
    ghrepo: ggseas
    tags: visualization,general
    cran: true
    release:
    examples:
    ghauthor: ellisp
    short: >
      Seasonal adjustment on the fly extension for ggplot2.
    description: >     